name: teknozone
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.17.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_reactive_ble: ^5.0.3
  permission_handler: ^10.2.0
  request_permission: ^2.1.4
  location_permissions: ^4.0.0
  date_format: ^2.0.7
  string_to_hex: ^0.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
